// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

using System;
using System.Runtime.InteropServices;

namespace LoopbackManager.Models;

public enum NETISO_FLAG
{
    NETISO_FLAG_FORCE_COMPUTE_BINARIES = 0x1,
    NETISO_FLAG_MAX = 0x2,
}

[StructLayout(LayoutKind.Sequential)]
public struct SID_AND_ATTRIBUTES
{
    public IntPtr Sid;
    public uint Attributes;
}

[StructLayout(LayoutKind.Sequential)]
public struct INET_FIREWALL_AC_CAPABILITIES
{
    public uint count;
    public IntPtr capabilities;
}

[StructLayout(LayoutKind.Sequential)]
public struct INET_FIREWALL_AC_BINARIES
{
    public uint count;
    public IntPtr binaries;
}

[StructLayout(LayoutKind.Sequential)]
public struct INET_FIREWALL_APP_CONTAINER
{
    public IntPtr appContainerSid;
    public IntPtr userSid;
    [MarshalAs(UnmanagedType.LPWStr)]
    public string appContainerName;
    [MarshalAs(UnmanagedType.LPWStr)]
    public string displayName;
    [MarshalAs(UnmanagedType.LPWStr)]
    public string description;
    public INET_FIREWALL_AC_CAPABILITIES capabilities;
    public INET_FIREWALL_AC_BINARIES binaries;
    [MarshalAs(UnmanagedType.LPWStr)]
    public string workingDirectory;
    [MarshalAs(UnmanagedType.LPWStr)]
    public string packageFullName;
}

