// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

namespace LoopbackManager.Models.Constants;

/// <summary>
/// 设置名.
/// </summary>
public enum SettingNames
{
    WindowWidth,
    WindowHeight,
    WindowPositionLeft,
    WindowPositionTop,
    IsMainWindowMaximized,
}
